"""sync_database_status_enum

Revision ID: 2b125aaa8fae
Revises: 
Create Date: 2026-03-15 16:33:34.779776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b125aaa8fae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_debts_fecha', table_name='debts')
    op.drop_index('idx_debts_status', table_name='debts')
    op.drop_index('idx_transactions_debt_id', table_name='transactions')
    op.drop_constraint('transactions_debt_id_fkey', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'debts', ['debt_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_debt_id_fkey', 'transactions', 'debts', ['debt_id'], ['id'], ondelete='SET NULL')
    op.create_index('idx_transactions_debt_id', 'transactions', ['debt_id'], unique=False)
    op.create_index('idx_debts_status', 'debts', ['status'], unique=False)
    op.create_index('idx_debts_fecha', 'debts', ['fecha'], unique=False)
    # ### end Alembic commands ###
