"""add_monthly_balances_and_rollover_columns

Revision ID: 47c34fcbcce0
Revises: a1b2c3d4e5f6
Create Date: 2026-05-04 14:16:50.052143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47c34fcbcce0'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_month', sa.String(length=7), nullable=False),
    sa.Column('target_month', sa.String(length=7), nullable=False),
    sa.Column('balance_amount', sa.Float(), nullable=False),
    sa.Column('balance_type', sa.String(length=20), nullable=False),
    sa.Column('carryover_date', sa.DateTime(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthly_balances_id'), 'monthly_balances', ['id'], unique=False)
    op.create_index(op.f('ix_monthly_balances_user_id'), 'monthly_balances', ['user_id'], unique=False)
    op.add_column('budget_items', sa.Column('cloned_from_item_id', sa.Integer(), nullable=True))
    op.add_column('budget_items', sa.Column('base_cloned', sa.Float(), nullable=True))
    op.add_column('budget_items', sa.Column('version_source_month', sa.String(length=7), nullable=True))
    op.create_foreign_key(None, 'budget_items', 'budget_items', ['cloned_from_item_id'], ['id'], ondelete='SET NULL')
    op.add_column('transactions', sa.Column('source_month', sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'source_month')
    op.drop_constraint(None, 'budget_items', type_='foreignkey')
    op.drop_column('budget_items', 'version_source_month')
    op.drop_column('budget_items', 'base_cloned')
    op.drop_column('budget_items', 'cloned_from_item_id')
    op.drop_index(op.f('ix_monthly_balances_user_id'), table_name='monthly_balances')
    op.drop_index(op.f('ix_monthly_balances_id'), table_name='monthly_balances')
    op.drop_table('monthly_balances')
    # ### end Alembic commands ###
