"""add_expense_type_to_budget_items

Revision ID: 6f05aa48cf28
Revises: 47c34fcbcce0
Create Date: 2026-05-05 17:35:58.472009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f05aa48cf28'
down_revision: Union[str, None] = '47c34fcbcce0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'budget_items',
        sa.Column(
            'expense_type',
            sa.Enum('FIJO', 'VARIABLE', name='expensetype'),
            nullable=False,
            server_default='VARIABLE'
        )
    )
    op.alter_column('budget_items', 'expense_type', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budget_items', 'expense_type')
    # ### end Alembic commands ###
