"""add_credit_card_management_module

Revision ID: e10c0b8c5dbe
Revises: 2b125aaa8fae
Create Date: 2026-03-26 11:50:42.429345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e10c0b8c5dbe'
down_revision: Union[str, None] = '2b125aaa8fae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('card_name', sa.String(length=100), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('closing_day', sa.Integer(), nullable=False),
    sa.Column('due_day', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('credit_limit', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_name')
    )
    op.create_index(op.f('ix_credit_cards_id'), 'credit_cards', ['id'], unique=False)
    op.create_table('credit_card_statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('statement_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('previous_balance', sa.Float(), nullable=True),
    sa.Column('total_purchases', sa.Float(), nullable=True),
    sa.Column('total_installments', sa.Float(), nullable=True),
    sa.Column('total_interest', sa.Float(), nullable=True),
    sa.Column('total_fees', sa.Float(), nullable=True),
    sa.Column('total_taxes', sa.Float(), nullable=True),
    sa.Column('total_credits', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('minimum_payment', sa.Float(), nullable=True),
    sa.Column('paid_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PARTIALLY_PAID', 'PAID', 'OVERDUE', name='statementstatus'), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['credit_cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_card_statements_id'), 'credit_card_statements', ['id'], unique=False)
    op.create_table('credit_card_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('statement_id', sa.Integer(), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['credit_cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['statement_id'], ['credit_card_statements.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_card_payments_id'), 'credit_card_payments', ['id'], unique=False)
    op.create_table('credit_card_purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('installments', sa.Integer(), nullable=True),
    sa.Column('has_financing', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['credit_cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_card_purchases_id'), 'credit_card_purchases', ['id'], unique=False)
    op.create_table('installment_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('debt_id', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('number_of_installments', sa.Integer(), nullable=False),
    sa.Column('interest_rate', sa.Float(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('plan_type', sa.Enum('REGULAR', 'PROMOTIONAL', 'ZERO_INTEREST', name='installmentplantype'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['debt_id'], ['debts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['purchase_id'], ['credit_card_purchases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purchase_id')
    )
    op.create_index(op.f('ix_installment_plans_id'), 'installment_plans', ['id'], unique=False)
    op.create_table('installment_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('installment_number', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('principal_amount', sa.Float(), nullable=False),
    sa.Column('interest_amount', sa.Float(), nullable=True),
    sa.Column('total_installment_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', name='installmentstatus'), nullable=True),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('payment_transaction_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['payment_transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_id'], ['installment_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_installment_schedule_id'), 'installment_schedule', ['id'], unique=False)
    
    # Create ENUM types if they don't exist (may exist from manual SQL migrations)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE budgettype AS ENUM ('OBLIGATION', 'VARIABLE');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE flowtype AS ENUM ('Gasto', 'Ingreso');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE assignmentstatus AS ENUM ('ASIGNADA_MANUAL', 'ASIGNADA_AUTOMATICA', 'NO_PLANIFICADA', 'REASIGNADA_AUTOMATICA');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    
    # Drop indexes before altering columns
    op.execute("DROP INDEX IF EXISTS idx_debts_tipo_flujo")
    op.execute("DROP INDEX IF EXISTS idx_debts_tipo_presupuesto")
    
    # Convert columns from VARCHAR to ENUM
    # Step 1: Drop defaults
    op.execute("ALTER TABLE debts ALTER COLUMN tipo_presupuesto DROP DEFAULT")
    op.execute("ALTER TABLE debts ALTER COLUMN tipo_flujo DROP DEFAULT")
    op.execute("ALTER TABLE transactions ALTER COLUMN estado_asignacion DROP DEFAULT")
    
    # Step 2: Convert types using USING clause
    op.execute("ALTER TABLE debts ALTER COLUMN tipo_presupuesto TYPE budgettype USING tipo_presupuesto::budgettype")
    op.execute("ALTER TABLE debts ALTER COLUMN tipo_flujo TYPE flowtype USING tipo_flujo::flowtype")
    op.execute("ALTER TABLE transactions ALTER COLUMN estado_asignacion TYPE assignmentstatus USING estado_asignacion::assignmentstatus")
    
    # Step 3: Set defaults back
    op.execute("ALTER TABLE debts ALTER COLUMN tipo_presupuesto SET DEFAULT 'OBLIGATION'::budgettype")
    op.execute("ALTER TABLE debts ALTER COLUMN tipo_flujo SET DEFAULT 'Gasto'::flowtype")
    op.execute("ALTER TABLE transactions ALTER COLUMN estado_asignacion SET DEFAULT 'ASIGNADA_MANUAL'::assignmentstatus")
    
    # Set NOT NULL constraints
    op.alter_column('debts', 'monto_ejecutado',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Convert ENUM back to VARCHAR
    op.execute("ALTER TABLE transactions ALTER COLUMN estado_asignacion TYPE VARCHAR(30) USING estado_asignacion::text")
    op.execute("ALTER TABLE debts ALTER COLUMN tipo_flujo TYPE VARCHAR(20) USING tipo_flujo::text")
    op.execute("ALTER TABLE debts ALTER COLUMN tipo_presupuesto TYPE VARCHAR(20) USING tipo_presupuesto::text")
    
    # Drop ENUM types
    op.execute("DROP TYPE IF EXISTS assignmentstatus")
    op.execute("DROP TYPE IF EXISTS flowtype")
    op.execute("DROP TYPE IF EXISTS budgettype")
    
    # Recreate indexes
    op.create_index('idx_debts_tipo_presupuesto', 'debts', ['tipo_presupuesto'], unique=False)
    op.create_index('idx_debts_tipo_flujo', 'debts', ['tipo_flujo'], unique=False)
    
    op.alter_column('debts', 'monto_ejecutado',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.drop_index(op.f('ix_installment_schedule_id'), table_name='installment_schedule')
    op.drop_table('installment_schedule')
    op.drop_index(op.f('ix_installment_plans_id'), table_name='installment_plans')
    op.drop_table('installment_plans')
    op.drop_index(op.f('ix_credit_card_purchases_id'), table_name='credit_card_purchases')
    op.drop_table('credit_card_purchases')
    op.drop_index(op.f('ix_credit_card_payments_id'), table_name='credit_card_payments')
    op.drop_table('credit_card_payments')
    op.drop_index(op.f('ix_credit_card_statements_id'), table_name='credit_card_statements')
    op.drop_table('credit_card_statements')
    op.drop_index(op.f('ix_credit_cards_id'), table_name='credit_cards')
    op.drop_table('credit_cards')
    # ### end Alembic commands ###
