"""add_monthly_periods_and_snapshots

Revision ID: e18b741c007c
Revises: d21f4e8a9c7b
Create Date: 2026-04-30 14:41:32.236931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e18b741c007c'
down_revision: Union[str, None] = 'd21f4e8a9c7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year_month', sa.String(length=7), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'REOPENED', name='monthperiodstatus'), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('closed_by', sa.Integer(), nullable=True),
    sa.Column('reopened_at', sa.DateTime(), nullable=True),
    sa.Column('reopened_by', sa.Integer(), nullable=True),
    sa.Column('reopen_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reopened_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthly_periods_id'), 'monthly_periods', ['id'], unique=False)
    op.create_index(op.f('ix_monthly_periods_year_month'), 'monthly_periods', ['year_month'], unique=True)
    op.create_table('monthly_period_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monthly_period_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(), nullable=False),
    sa.Column('total_expenses', sa.Float(), nullable=False),
    sa.Column('total_income', sa.Float(), nullable=False),
    sa.Column('net_balance', sa.Float(), nullable=False),
    sa.Column('transaction_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['monthly_period_id'], ['monthly_periods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthly_period_snapshots_id'), 'monthly_period_snapshots', ['id'], unique=False)
    op.drop_index('ix_transactions_demo_id', table_name='transactions_demo', postgresql_with={'fillfactor': '100', 'deduplicate_items': 'true'})
    op.drop_table('transactions_demo')
    op.drop_table('test_123')
    op.alter_column('budget_items', 'tipo_presupuesto',
               existing_type=postgresql.ENUM('OBLIGATION', 'VARIABLE', name='budgettype'),
               nullable=False,
               existing_server_default=sa.text("'OBLIGATION'::budgettype"))
    op.alter_column('budget_items', 'tipo_flujo',
               existing_type=postgresql.ENUM('Gasto', 'Ingreso', name='flowtype'),
               nullable=False,
               existing_server_default=sa.text("'Gasto'::flowtype"))
    op.drop_index('ix_debts_id', table_name='budget_items')
    op.create_index(op.f('ix_budget_items_id'), 'budget_items', ['id'], unique=False)
    op.add_column('transactions', sa.Column('origin', sa.String(length=50), nullable=False, server_default='MANUAL'))
    op.add_column('transactions', sa.Column('monthly_period_id', sa.Integer(), nullable=True))
    op.alter_column('transactions', 'assignment_status',
               existing_type=postgresql.ENUM('ASIGNADA_MANUAL', 'ASIGNADA_AUTOMATICA', 'NO_PLANIFICADA', 'REASIGNADA_AUTOMATICA', name='assignmentstatus'),
               nullable=False,
               existing_server_default=sa.text("'ASIGNADA_MANUAL'::assignmentstatus"))
    op.create_foreign_key(None, 'transactions', 'monthly_periods', ['monthly_period_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.alter_column('transactions', 'assignment_status',
               existing_type=postgresql.ENUM('ASIGNADA_MANUAL', 'ASIGNADA_AUTOMATICA', 'NO_PLANIFICADA', 'REASIGNADA_AUTOMATICA', name='assignmentstatus'),
               nullable=True,
               existing_server_default=sa.text("'ASIGNADA_MANUAL'::assignmentstatus"))
    op.drop_column('transactions', 'monthly_period_id')
    op.drop_column('transactions', 'origin')
    op.drop_index(op.f('ix_budget_items_id'), table_name='budget_items')
    op.create_index('ix_debts_id', 'budget_items', ['id'], unique=False)
    op.alter_column('budget_items', 'tipo_flujo',
               existing_type=postgresql.ENUM('Gasto', 'Ingreso', name='flowtype'),
               nullable=True,
               existing_server_default=sa.text("'Gasto'::flowtype"))
    op.alter_column('budget_items', 'tipo_presupuesto',
               existing_type=postgresql.ENUM('OBLIGATION', 'VARIABLE', name='budgettype'),
               nullable=True,
               existing_server_default=sa.text("'OBLIGATION'::budgettype"))
    op.create_table('test_123',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('transactions_demo',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('GASTO', 'INGRESO', name='transactiontype'), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('necessity', postgresql.ENUM('NECESARIO', 'SUPERFLUO', 'IMPORTANTE_NO_URGENTE', name='necessitytype'), autoincrement=False, nullable=False),
    sa.Column('payment_method', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('detail', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('debt_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('assignment_status', postgresql.ENUM('ASIGNADA_MANUAL', 'ASIGNADA_AUTOMATICA', 'NO_PLANIFICADA', 'REASIGNADA_AUTOMATICA', name='assignmentstatus'), server_default=sa.text("'ASIGNADA_MANUAL'::assignmentstatus"), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='transactions_demo_category_id_fkey'),
    sa.ForeignKeyConstraint(['debt_id'], ['budget_items.id'], name='transactions_demo_debt_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='transactions_demo_pkey')
    )
    op.create_index('ix_transactions_demo_id', 'transactions_demo', ['id'], unique=False, postgresql_with={'fillfactor': '100', 'deduplicate_items': 'true'})
    op.drop_index(op.f('ix_monthly_period_snapshots_id'), table_name='monthly_period_snapshots')
    op.drop_table('monthly_period_snapshots')
    op.drop_index(op.f('ix_monthly_periods_year_month'), table_name='monthly_periods')
    op.drop_index(op.f('ix_monthly_periods_id'), table_name='monthly_periods')
    op.drop_table('monthly_periods')
    # ### end Alembic commands ###
